apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hello-world
spec:
  secretName: hello-world
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - hello-world.<your-domain>
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - hello-world.<your-domain>